### ISSUE TITLE
Calculate min/max for each axis

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium/react-plot#348]
in https://github.com/zakodium/react-plot/blob/f863af361e85c572a0f270baafa35bbd9abb5a16/src/contexts/plotContext.ts#L199
where we are calculating axis max/min in general for horizontal axes and vertical axes
but we can make it better by calculating min/max for every axis

it will be very usefull
for example :

```
<Plot>
       <LineSeries
        yAxis="z"
        label="rainfall"
        data={rainfall }
      />
      <LineSeries
        yAxis="y"
        label="temperature"
        data={temperature}
      />
      <Axis id="x" position="bottom" label="time [s]" scale="time" />
      <Axis id="y" position="left" />
      <Axis id="z" position="right" />
</Plot>
```
in this example we're using rainfall lineSerie and temperature lineSerie which we can't use the same vertical axis (C°  / mm)

**Comment by targos** [comment]
The bug is in those two lines:

https://github.com/zakodium/react-plot/blob/f863af361e85c572a0f270baafa35bbd9abb5a16/src/contexts/plotContext.ts#L211
https://github.com/zakodium/react-plot/blob/f863af361e85c572a0f270baafa35bbd9abb5a16/src/contexts/plotContext.ts#L223

We should only use the series that are associated to the current axis (being treated in the loop).

**Comment by targos** [comment]
@wadjih-bencheikh18 can you fix this?

**Comment by wadjih-bencheikh18** [comment]
yes i'm going to try
